version: "2"
services:
#  zh_dev:
#    image: eabax_zh_dev_docker
#    restart: always
#    container_name: zh_dev
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./conf.d:/etc/nginx/conf.d
#    links:
#      - zh_dev
    ports:
      - 80:80
